version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
      MYSQL_DATABASE: baz
