logging:
  level:
    web: info

spring:
  rsocket:
    server:
      transport: websocket
      port: 7000
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:13306/baz
    username: foo
    password: bar
    pool.initial-size: 10
    pool.max-size: 100
    pool.max-idle-time: 30m
    pool.validation-query: SELECT 1