SET CHARSET UTF8;
SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

USE baz;

DROP TABLE IF EXISTS address;

CREATE TABLE address
(
  zip VARCHAR(10),
  state     VARCHAR(255),
  city     VARCHAR(255),
  address_line VARCHAR(255)
) DEFAULT CHARSET = utf8;

INSERT INTO address VALUES  ('600000','北海道','札幌市　中央区','以下に掲載がない場合');
INSERT INTO address VALUES  ('640941','北海道','札幌市　中央区','旭ケ丘');
INSERT INTO address VALUES  ('600041','北海道','札幌市　中央区','大通東');
INSERT INTO address VALUES  ('600042','北海道','札幌市　中央区','大通西（１～１９丁目）');
INSERT INTO address VALUES  ('640820','北海道','札幌市　中央区','大通西（２０～２８丁目）');
INSERT INTO address VALUES  ('600031','北海道','札幌市　中央区','北一条東');
INSERT INTO address VALUES  ('600001','北海道','札幌市　中央区','北一条西（１～１９丁目）');
INSERT INTO address VALUES  ('640821','北海道','札幌市　中央区','北一条西（２０～２８丁目）');
INSERT INTO address VALUES  ('600032','北海道','札幌市　中央区','北二条東');
INSERT INTO address VALUES  ('600002','北海道','札幌市　中央区','北二条西（１～１９丁目）');
INSERT INTO address VALUES  ('640822','北海道','札幌市　中央区','北二条西（２０～２８丁目）');
INSERT INTO address VALUES  ('600033','北海道','札幌市　中央区','北三条東');
INSERT INTO address VALUES  ('600003','北海道','札幌市　中央区','北三条西（１～１９丁目）');
INSERT INTO address VALUES  ('640823','北海道','札幌市　中央区','北三条西（２０～３０丁目）');
INSERT INTO address VALUES  ('600034','北海道','札幌市　中央区','北四条東（１～８丁目）');
INSERT INTO address VALUES  ('600004','北海道','札幌市　中央区','北四条西（１～１９丁目）');
INSERT INTO address VALUES  ('640824','北海道','札幌市　中央区','北四条西（２０～３０丁目）');
INSERT INTO address VALUES  ('600035','北海道','札幌市　中央区','北五条東');
INSERT INTO address VALUES  ('600005','北海道','札幌市　中央区','北五条西（１～２４丁目）');
INSERT INTO address VALUES  ('640825','北海道','札幌市　中央区','北五条西（２５～２９丁目）');
INSERT INTO address VALUES  ('600006','北海道','札幌市　中央区','北六条西（１０～２５丁目）');
INSERT INTO address VALUES  ('640826','北海道','札幌市　中央区','北六条西（２６～２８丁目）');
INSERT INTO address VALUES  ('600007','北海道','札幌市　中央区','北七条西');
INSERT INTO address VALUES  ('600008','北海道','札幌市　中央区','北八条西');
INSERT INTO address VALUES  ('600009','北海道','札幌市　中央区','北九条西');
INSERT INTO address VALUES  ('600010','北海道','札幌市　中央区','北十条西');
INSERT INTO address VALUES  ('600011','北海道','札幌市　中央区','北十一条西');
INSERT INTO address VALUES  ('600012','北海道','札幌市　中央区','北十二条西');
INSERT INTO address VALUES  ('600013','北海道','札幌市　中央区','北十三条西');
INSERT INTO address VALUES  ('600014','北海道','札幌市　中央区','北十四条西');
INSERT INTO address VALUES  ('600015','北海道','札幌市　中央区','北十五条西');
INSERT INTO address VALUES  ('600016','北海道','札幌市　中央区','北十六条西');
INSERT INTO address VALUES  ('600017','北海道','札幌市　中央区','北十七条西');
INSERT INTO address VALUES  ('600018','北海道','札幌市　中央区','北十八条西');
INSERT INTO address VALUES  ('600020','北海道','札幌市　中央区','北二十条西');
INSERT INTO address VALUES  ('600021','北海道','札幌市　中央区','北二十一条西');
INSERT INTO address VALUES  ('600022','北海道','札幌市　中央区','北二十二条西');
INSERT INTO address VALUES  ('640943','北海道','札幌市　中央区','界川');
INSERT INTO address VALUES  ('640931','北海道','札幌市　中央区','中島公園');
INSERT INTO address VALUES  ('640945','北海道','札幌市　中央区','盤渓');
INSERT INTO address VALUES  ('640942','北海道','札幌市　中央区','伏見');
INSERT INTO address VALUES  ('640946','北海道','札幌市　中央区','双子山');
INSERT INTO address VALUES  ('640944','北海道','札幌市　中央区','円山西町');
INSERT INTO address VALUES  ('600051','北海道','札幌市　中央区','南一条東');
INSERT INTO address VALUES  ('600061','北海道','札幌市　中央区','南一条西（１～１９丁目）');
INSERT INTO address VALUES  ('640801','北海道','札幌市　中央区','南一条西（２０～２８丁目）');
INSERT INTO address VALUES  ('600052','北海道','札幌市　中央区','南二条東');
INSERT INTO address VALUES  ('600062','北海道','札幌市　中央区','南二条西（１～１９丁目）');
INSERT INTO address VALUES  ('640802','北海道','札幌市　中央区','南二条西（２０～２８丁目）');
INSERT INTO address VALUES  ('600053','北海道','札幌市　中央区','南三条東');
INSERT INTO address VALUES  ('600063','北海道','札幌市　中央区','南三条西（１～１８丁目）');
INSERT INTO address VALUES  ('640803','北海道','札幌市　中央区','南三条西（２０～２８丁目）');
INSERT INTO address VALUES  ('600054','北海道','札幌市　中央区','南四条東');
INSERT INTO address VALUES  ('640804','北海道','札幌市　中央区','南四条西');
INSERT INTO address VALUES  ('600055','北海道','札幌市　中央区','南五条東');
INSERT INTO address VALUES  ('640805','北海道','札幌市　中央区','南五条西');
INSERT INTO address VALUES  ('600056','北海道','札幌市　中央区','南六条東');
INSERT INTO address VALUES  ('640806','北海道','札幌市　中央区','南六条西');
INSERT INTO address VALUES  ('600057','北海道','札幌市　中央区','南七条東');
INSERT INTO address VALUES  ('640807','北海道','札幌市　中央区','南七条西');
INSERT INTO address VALUES  ('640808','北海道','札幌市　中央区','南八条西');
INSERT INTO address VALUES  ('640809','北海道','札幌市　中央区','南九条西');
INSERT INTO address VALUES  ('640810','北海道','札幌市　中央区','南十条西');
INSERT INTO address VALUES  ('640811','北海道','札幌市　中央区','南十一条西');
INSERT INTO address VALUES  ('640912','北海道','札幌市　中央区','南十二条西');
INSERT INTO address VALUES  ('640913','北海道','札幌市　中央区','南十三条西');
INSERT INTO address VALUES  ('640914','北海道','札幌市　中央区','南十四条西');
INSERT INTO address VALUES  ('640915','北海道','札幌市　中央区','南十五条西');
INSERT INTO address VALUES  ('640916','北海道','札幌市　中央区','南十六条西');
INSERT INTO address VALUES  ('640917','北海道','札幌市　中央区','南十七条西');
INSERT INTO address VALUES  ('640918','北海道','札幌市　中央区','南十八条西');
INSERT INTO address VALUES  ('640919','北海道','札幌市　中央区','南十九条西');
INSERT INTO address VALUES  ('640920','北海道','札幌市　中央区','南二十条西');
INSERT INTO address VALUES  ('640921','北海道','札幌市　中央区','南二十一条西');
INSERT INTO address VALUES  ('640922','北海道','札幌市　中央区','南二十二条西');
INSERT INTO address VALUES  ('640923','北海道','札幌市　中央区','南二十三条西');
INSERT INTO address VALUES  ('640924','北海道','札幌市　中央区','南二十四条西');
INSERT INTO address VALUES  ('640925','北海道','札幌市　中央区','南二十五条西');
INSERT INTO address VALUES  ('640926','北海道','札幌市　中央区','南二十六条西');
INSERT INTO address VALUES  ('640927','北海道','札幌市　中央区','南二十七条西');
INSERT INTO address VALUES  ('640928','北海道','札幌市　中央区','南二十八条西');
INSERT INTO address VALUES  ('640929','北海道','札幌市　中央区','南二十九条西');
INSERT INTO address VALUES  ('640930','北海道','札幌市　中央区','南三十条西（９～１１丁目）');
INSERT INTO address VALUES  ('640959','北海道','札幌市　中央区','宮ケ丘');
INSERT INTO address VALUES  ('640958','北海道','札幌市　中央区','宮の森');
INSERT INTO address VALUES  ('640951','北海道','札幌市　中央区','宮の森　一条');
INSERT INTO address VALUES  ('640952','北海道','札幌市　中央区','宮の森　二条');
INSERT INTO address VALUES  ('640953','北海道','札幌市　中央区','宮の森　三条');
INSERT INTO address VALUES  ('640954','北海道','札幌市　中央区','宮の森　四条');
INSERT INTO address VALUES  ('10000','北海道','札幌市　北区','以下に掲載がない場合');
INSERT INTO address VALUES  ('28071','北海道','札幌市　北区','あいの里　一条');
INSERT INTO address VALUES  ('28072','北海道','札幌市　北区','あいの里　二条');
INSERT INTO address VALUES  ('28073','北海道','札幌市　北区','あいの里　三条');
INSERT INTO address VALUES  ('28074','北海道','札幌市　北区','あいの里　四条');
INSERT INTO address VALUES  ('28075','北海道','札幌市　北区','あいの里　五条');
INSERT INTO address VALUES  ('10045','北海道','札幌市　北区','麻生町');
INSERT INTO address VALUES  ('600806','北海道','札幌市　北区','北六条西');
INSERT INTO address VALUES  ('600807','北海道','札幌市　北区','北七条西');
INSERT INTO address VALUES  ('600808','北海道','札幌市　北区','北八条西');
INSERT INTO address VALUES  ('600809','北海道','札幌市　北区','北九条西');
INSERT INTO address VALUES  ('10010','北海道','札幌市　北区','北十条西（１～４丁目）');
INSERT INTO address VALUES  ('600810','北海道','札幌市　北区','北十条西（５～１１丁目）');
INSERT INTO address VALUES  ('10011','北海道','札幌市　北区','北十一条西（１～４丁目）');
INSERT INTO address VALUES  ('600811','北海道','札幌市　北区','北十一条西（５～１１丁目）');
INSERT INTO address VALUES  ('10012','北海道','札幌市　北区','北十二条西（１～４丁目）');
INSERT INTO address VALUES  ('600812','北海道','札幌市　北区','北十二条西（５～１２丁目）');
INSERT INTO address VALUES  ('10013','北海道','札幌市　北区','北十三条西（１～４丁目）');
INSERT INTO address VALUES  ('600813','北海道','札幌市　北区','北十三条西（５～１２丁目）');
INSERT INTO address VALUES  ('10014','北海道','札幌市　北区','北十四条西（１～４丁目）');
INSERT INTO address VALUES  ('600814','北海道','札幌市　北区','北十四条西（５～１３丁目）');
INSERT INTO address VALUES  ('10015','北海道','札幌市　北区','北十五条西（１～５丁目）');
INSERT INTO address VALUES  ('600815','北海道','札幌市　北区','北十五条西（６～１３丁目）');
INSERT INTO address VALUES  ('10016','北海道','札幌市　北区','北十六条西（１～６丁目）');
INSERT INTO address VALUES  ('600816','北海道','札幌市　北区','北十六条西（７～１３丁目）');
INSERT INTO address VALUES  ('10017','北海道','札幌市　北区','北十七条西（１～６丁目）');
INSERT INTO address VALUES  ('600817','北海道','札幌市　北区','北十七条西（７～１３丁目）');
INSERT INTO address VALUES  ('10018','北海道','札幌市　北区','北十八条西（１～７丁目）');
INSERT INTO address VALUES  ('600818','北海道','札幌市　北区','北十八条西（８～１３丁目）');
INSERT INTO address VALUES  ('10019','北海道','札幌市　北区','北十九条西（２～７丁目）');
INSERT INTO address VALUES  ('600819','北海道','札幌市　北区','北十九条西（８～１３丁目）');
INSERT INTO address VALUES  ('10020','北海道','札幌市　北区','北二十条西（２～１０丁目）');
INSERT INTO address VALUES  ('600820','北海道','札幌市　北区','北二十条西（１１～１３丁目）');
INSERT INTO address VALUES  ('10021','北海道','札幌市　北区','北二十一条西');
INSERT INTO address VALUES  ('10022','北海道','札幌市　北区','北二十二条西');
INSERT INTO address VALUES  ('10023','北海道','札幌市　北区','北二十三条西');
INSERT INTO address VALUES  ('10024','北海道','札幌市　北区','北二十四条西');
INSERT INTO address VALUES  ('10025','北海道','札幌市　北区','北二十五条西');
INSERT INTO address VALUES  ('10026','北海道','札幌市　北区','北二十六条西');
INSERT INTO address VALUES  ('10027','北海道','札幌市　北区','北二十七条西');
INSERT INTO address VALUES  ('10028','北海道','札幌市　北区','北二十八条西');
INSERT INTO address VALUES  ('10029','北海道','札幌市　北区','北二十九条西');
INSERT INTO address VALUES  ('10030','北海道','札幌市　北区','北三十条西');
INSERT INTO address VALUES  ('10031','北海道','札幌市　北区','北三十一条西');
INSERT INTO address VALUES  ('10032','北海道','札幌市　北区','北三十二条西');
INSERT INTO address VALUES  ('10033','北海道','札幌市　北区','北三十三条西');
INSERT INTO address VALUES  ('10034','北海道','札幌市　北区','北三十四条西');
INSERT INTO address VALUES  ('10035','北海道','札幌市　北区','北三十五条西');
INSERT INTO address VALUES  ('10036','北海道','札幌市　北区','北三十六条西');
INSERT INTO address VALUES  ('10037','北海道','札幌市　北区','北三十七条西');
INSERT INTO address VALUES  ('10038','北海道','札幌市　北区','北三十八条西');
INSERT INTO address VALUES  ('10039','北海道','札幌市　北区','北三十九条西');
INSERT INTO address VALUES  ('10040','北海道','札幌市　北区','北四十条西');
INSERT INTO address VALUES  ('28021','北海道','札幌市　北区','篠路　一条');
INSERT INTO address VALUES  ('28022','北海道','札幌市　北区','篠路　二条');
INSERT INTO address VALUES  ('28023','北海道','札幌市　北区','篠路　三条');
INSERT INTO address VALUES  ('28024','北海道','札幌市　北区','篠路　四条');
INSERT INTO address VALUES  ('28025','北海道','札幌市　北区','篠路　五条');
INSERT INTO address VALUES  ('28026','北海道','札幌市　北区','篠路　六条');
INSERT INTO address VALUES  ('28027','北海道','札幌市　北区','篠路　七条');
INSERT INTO address VALUES  ('28028','北海道','札幌市　北区','篠路　八条');
INSERT INTO address VALUES  ('28029','北海道','札幌市　北区','篠路　九条');
INSERT INTO address VALUES  ('28030','北海道','札幌市　北区','篠路　十条');
INSERT INTO address VALUES  ('28052','北海道','札幌市　北区','篠路町　上篠路');
INSERT INTO address VALUES  ('28053','北海道','札幌市　北区','篠路町　篠路');
INSERT INTO address VALUES  ('28051','北海道','札幌市　北区','篠路町　太平');
INSERT INTO address VALUES  ('28054','北海道','札幌市　北区','篠路町　拓北');
INSERT INTO address VALUES  ('28055','北海道','札幌市　北区','篠路町　福移');
INSERT INTO address VALUES  ('10930','北海道','札幌市　北区','新川');
INSERT INTO address VALUES  ('10921','北海道','札幌市　北区','新川　一条');
INSERT INTO address VALUES  ('10922','北海道','札幌市　北区','新川　二条');
INSERT INTO address VALUES  ('10923','北海道','札幌市　北区','新川　三条');
INSERT INTO address VALUES  ('10924','北海道','札幌市　北区','新川　四条');
INSERT INTO address VALUES  ('10925','北海道','札幌市　北区','新川　五条');
INSERT INTO address VALUES  ('10926','北海道','札幌市　北区','新川　六条');
INSERT INTO address VALUES  ('10927','北海道','札幌市　北区','新川　七条');
INSERT INTO address VALUES  ('10928','北海道','札幌市　北区','新川　八条');
INSERT INTO address VALUES  ('10931','北海道','札幌市　北区','新川西　一条');
INSERT INTO address VALUES  ('10932','北海道','札幌市　北区','新川西　二条');
INSERT INTO address VALUES  ('10933','北海道','札幌市　北区','新川西　三条');
INSERT INTO address VALUES  ('10934','北海道','札幌市　北区','新川西　四条');
INSERT INTO address VALUES  ('10935','北海道','札幌市　北区','新川西　五条');
INSERT INTO address VALUES  ('10901','北海道','札幌市　北区','新琴似　一条');
INSERT INTO address VALUES  ('10902','北海道','札幌市　北区','新琴似　二条');
INSERT INTO address VALUES  ('10903','北海道','札幌市　北区','新琴似　三条');
INSERT INTO address VALUES  ('10904','北海道','札幌市　北区','新琴似　四条');
INSERT INTO address VALUES  ('10905','北海道','札幌市　北区','新琴似　五条');
INSERT INTO address VALUES  ('10906','北海道','札幌市　北区','新琴似　六条');
INSERT INTO address VALUES  ('10907','北海道','札幌市　北区','新琴似　七条');
INSERT INTO address VALUES  ('10908','北海道','札幌市　北区','新琴似　八条');
INSERT INTO address VALUES  ('10909','北海道','札幌市　北区','新琴似　九条');
INSERT INTO address VALUES  ('10910','北海道','札幌市　北区','新琴似　十条');
INSERT INTO address VALUES  ('10911','北海道','札幌市　北区','新琴似　十一条');
INSERT INTO address VALUES  ('10912','北海道','札幌市　北区','新琴似　十二条');
INSERT INTO address VALUES  ('10915','北海道','札幌市　北区','新琴似町');
INSERT INTO address VALUES  ('28001','北海道','札幌市　北区','太平　一条');
INSERT INTO address VALUES  ('28002','北海道','札幌市　北区','太平　二条');
INSERT INTO address VALUES  ('28003','北海道','札幌市　北区','太平　三条');
INSERT INTO address VALUES  ('28004','北海道','札幌市　北区','太平　四条');
INSERT INTO address VALUES  ('28005','北海道','札幌市　北区','太平　五条');
INSERT INTO address VALUES  ('28006','北海道','札幌市　北区','太平　六条');
INSERT INTO address VALUES  ('28007','北海道','札幌市　北区','太平　七条');
INSERT INTO address VALUES  ('28008','北海道','札幌市　北区','太平　八条');
INSERT INTO address VALUES  ('28009','北海道','札幌市　北区','太平　九条');
INSERT INTO address VALUES  ('28010','北海道','札幌市　北区','太平　十条');
INSERT INTO address VALUES  ('28011','北海道','札幌市　北区','太平　十一条');
INSERT INTO address VALUES  ('28012','北海道','札幌市　北区','太平　十二条');
INSERT INTO address VALUES  ('28061','北海道','札幌市　北区','拓北　一条');
INSERT INTO address VALUES  ('28062','北海道','札幌市　北区','拓北　二条');
INSERT INTO address VALUES  ('28063','北海道','札幌市　北区','拓北　三条');
INSERT INTO address VALUES  ('28064','北海道','札幌市　北区','拓北　四条');
INSERT INTO address VALUES  ('28065','北海道','札幌市　北区','拓北　五条');
INSERT INTO address VALUES  ('28066','北海道','札幌市　北区','拓北　六条');
INSERT INTO address VALUES  ('28067','北海道','札幌市　北区','拓北　七条');
INSERT INTO address VALUES  ('28068','北海道','札幌市　北区','拓北　八条');
INSERT INTO address VALUES  ('20851','北海道','札幌市　北区','屯田　一条');
INSERT INTO address VALUES  ('20852','北海道','札幌市　北区','屯田　二条');
INSERT INTO address VALUES  ('20853','北海道','札幌市　北区','屯田　三条');
INSERT INTO address VALUES  ('20854','北海道','札幌市　北区','屯田　四条');
INSERT INTO address VALUES  ('20855','北海道','札幌市　北区','屯田　五条');
INSERT INTO address VALUES  ('20856','北海道','札幌市　北区','屯田　六条');
INSERT INTO address VALUES  ('20857','北海道','札幌市　北区','屯田　七条');
INSERT INTO address VALUES  ('20858','北海道','札幌市　北区','屯田　八条');
INSERT INTO address VALUES  ('20859','北海道','札幌市　北区','屯田　九条');
INSERT INTO address VALUES  ('20860','北海道','札幌市　北区','屯田　十条');
INSERT INTO address VALUES  ('20861','北海道','札幌市　北区','屯田　十一条');
INSERT INTO address VALUES  ('20865','北海道','札幌市　北区','屯田町');
INSERT INTO address VALUES  ('28038','北海道','札幌市　北区','西茨戸');
INSERT INTO address VALUES  ('28031','北海道','札幌市　北区','西茨戸　一条');
INSERT INTO address VALUES  ('28032','北海道','札幌市　北区','西茨戸　二条');
INSERT INTO address VALUES  ('28033','北海道','札幌市　北区','西茨戸　三条');
INSERT INTO address VALUES  ('28034','北海道','札幌市　北区','西茨戸　四条');
INSERT INTO address VALUES  ('28035','北海道','札幌市　北区','西茨戸　五条');
INSERT INTO address VALUES  ('28036','北海道','札幌市　北区','西茨戸　六条');
INSERT INTO address VALUES  ('28037','北海道','札幌市　北区','西茨戸　七条');
INSERT INTO address VALUES  ('28043','北海道','札幌市　北区','東茨戸');
INSERT INTO address VALUES  ('28041','北海道','札幌市　北区','東茨戸　一条');
INSERT INTO address VALUES  ('28042','北海道','札幌市　北区','東茨戸　二条');
INSERT INTO address VALUES  ('28044','北海道','札幌市　北区','東茨戸　三条');
INSERT INTO address VALUES  ('28045','北海道','札幌市　北区','東茨戸　四条');
INSERT INTO address VALUES  ('28091','北海道','札幌市　北区','南あいの里');
INSERT INTO address VALUES  ('28081','北海道','札幌市　北区','百合が原');
INSERT INTO address VALUES  ('28082','北海道','札幌市　北区','百合が原公園');
INSERT INTO address VALUES  ('650000','北海道','札幌市　東区','以下に掲載がない場合');
INSERT INTO address VALUES  ('70880','北海道','札幌市　東区','丘珠町');
INSERT INTO address VALUES  ('70881','北海道','札幌市　東区','北丘珠　一条');
INSERT INTO address VALUES  ('70882','北海道','札幌市　東区','北丘珠　二条');
INSERT INTO address VALUES  ('70883','北海道','札幌市　東区','北丘珠　三条');
INSERT INTO address VALUES  ('70884','北海道','札幌市　東区','北丘珠　四条');
INSERT INTO address VALUES  ('70885','北海道','札幌市　東区','北丘珠　五条');
INSERT INTO address VALUES  ('70886','北海道','札幌市　東区','北丘珠　六条');
INSERT INTO address VALUES  ('650004','北海道','札幌市　東区','北四条東（９～１６丁目）');
INSERT INTO address VALUES  ('600905','北海道','札幌市　東区','北五条東（４～７丁目）');
INSERT INTO address VALUES  ('650005','北海道','札幌市　東区','北五条東（８～１７丁目）');
INSERT INTO address VALUES  ('600906','北海道','札幌市　東区','北六条東（１～７丁目）');
INSERT INTO address VALUES  ('650006','北海道','札幌市　東区','北六条東（８～２０丁目）');
INSERT INTO address VALUES  ('600907','北海道','札幌市　東区','北七条東（１～７丁目）');
INSERT INTO address VALUES  ('650007','北海道','札幌市　東区','北七条東（８～２０丁目）');
INSERT INTO address VALUES  ('600908','北海道','札幌市　東区','北八条東（１～７丁目）');
INSERT INTO address VALUES  ('650008','北海道','札幌市　東区','北八条東（８～１９丁目）');
INSERT INTO address VALUES  ('600909','北海道','札幌市　東区','北九条東（１～７丁目）');
INSERT INTO address VALUES  ('650009','北海道','札幌市　東区','北九条東（８～１６丁目）');
INSERT INTO address VALUES  ('650010','北海道','札幌市　東区','北十条東');
INSERT INTO address VALUES  ('650011','北海道','札幌市　東区','北十一条東');
INSERT INTO address VALUES  ('650012','北海道','札幌市　東区','北十二条東');
INSERT INTO address VALUES  ('650013','北海道','札幌市　東区','北十三条東');
INSERT INTO address VALUES  ('650014','北海道','札幌市　東区','北十四条東');
INSERT INTO address VALUES  ('650015','北海道','札幌市　東区','北十五条東');
INSERT INTO address VALUES  ('650016','北海道','札幌市　東区','北十六条東');
INSERT INTO address VALUES  ('650017','北海道','札幌市　東区','北十七条東');
INSERT INTO address VALUES  ('650018','北海道','札幌市　東区','北十八条東');
INSERT INTO address VALUES  ('650019','北海道','札幌市　東区','北十九条東');
INSERT INTO address VALUES  ('650020','北海道','札幌市　東区','北二十条東');
INSERT INTO address VALUES  ('650021','北海道','札幌市　東区','北二十一条東');
INSERT INTO address VALUES  ('650022','北海道','札幌市　東区','北二十二条東');
INSERT INTO address VALUES  ('650023','北海道','札幌市　東区','北二十三条東');
INSERT INTO address VALUES  ('650024','北海道','札幌市　東区','北二十四条東');
INSERT INTO address VALUES  ('650025','北海道','札幌市　東区','北二十五条東');
INSERT INTO address VALUES  ('650026','北海道','札幌市　東区','北二十六条東');
INSERT INTO address VALUES  ('650027','北海道','札幌市　東区','北二十七条東');
INSERT INTO address VALUES  ('650028','北海道','札幌市　東区','北二十八条東');
INSERT INTO address VALUES  ('650030','北海道','札幌市　東区','北三十条東');
INSERT INTO address VALUES  ('650031','北海道','札幌市　東区','北三十一条東');
INSERT INTO address VALUES  ('650032','北海道','札幌市　東区','北三十二条東');
INSERT INTO address VALUES  ('650033','北海道','札幌市　東区','北三十三条東');
INSERT INTO address VALUES  ('70834','北海道','札幌市　東区','北三十四条東');
INSERT INTO address VALUES  ('70835','北海道','札幌市　東区','北三十五条東');
INSERT INTO address VALUES  ('70836','北海道','札幌市　東区','北三十六条東');
INSERT INTO address VALUES  ('70837','北海道','札幌市　東区','北三十七条東');
INSERT INTO address VALUES  ('70838','北海道','札幌市　東区','北三十八条東');
INSERT INTO address VALUES  ('70839','北海道','札幌市　東区','北三十九条東');
INSERT INTO address VALUES  ('70840','北海道','札幌市　東区','北四十条東');
INSERT INTO address VALUES  ('70841','北海道','札幌市　東区','北四十一条東');
INSERT INTO address VALUES  ('70842','北海道','札幌市　東区','北四十二条東');
INSERT INTO address VALUES  ('70843','北海道','札幌市　東区','北四十三条東');
INSERT INTO address VALUES  ('70844','北海道','札幌市　東区','北四十四条東');
INSERT INTO address VALUES  ('70845','北海道','札幌市　東区','北四十五条東');
INSERT INTO address VALUES  ('70846','北海道','札幌市　東区','北四十六条東');
INSERT INTO address VALUES  ('70847','北海道','札幌市　東区','北四十七条東');
INSERT INTO address VALUES  ('70848','北海道','札幌市　東区','北四十八条東');
INSERT INTO address VALUES  ('70849','北海道','札幌市　東区','北四十九条東');
INSERT INTO address VALUES  ('70850','北海道','札幌市　東区','北五十条東');
INSERT INTO address VALUES  ('70851','北海道','札幌市　東区','北五十一条東');
INSERT INTO address VALUES  ('70852','北海道','札幌市　東区','栄町');
INSERT INTO address VALUES  ('650043','北海道','札幌市　東区','苗穂町');
INSERT INTO address VALUES  ('70001','北海道','札幌市　東区','中沼　一条');
INSERT INTO address VALUES  ('70002','北海道','札幌市　東区','中沼　二条');
INSERT INTO address VALUES  ('70003','北海道','札幌市　東区','中沼　三条');
INSERT INTO address VALUES  ('70004','北海道','札幌市　東区','中沼　四条');
INSERT INTO address VALUES  ('70005','北海道','札幌市　東区','中沼　五条');
INSERT INTO address VALUES  ('70006','北海道','札幌市　東区','中沼　六条');
INSERT INTO address VALUES  ('70890','北海道','札幌市　東区','中沼町');
INSERT INTO address VALUES  ('70891','北海道','札幌市　東区','中沼西　一条');
INSERT INTO address VALUES  ('70892','北海道','札幌市　東区','中沼西　二条');
INSERT INTO address VALUES  ('70893','北海道','札幌市　東区','中沼西　三条');
INSERT INTO address VALUES  ('70894','北海道','札幌市　東区','中沼西　四条');
INSERT INTO address VALUES  ('70895','北海道','札幌市　東区','中沼西　五条');
INSERT INTO address VALUES  ('70821','北海道','札幌市　東区','東雁来　一条');
INSERT INTO address VALUES  ('70822','北海道','札幌市　東区','東雁来　二条');
INSERT INTO address VALUES  ('70823','北海道','札幌市　東区','東雁来　三条');
INSERT INTO address VALUES  ('70824','北海道','札幌市　東区','東雁来　四条');
INSERT INTO address VALUES  ('70825','北海道','札幌市　東区','東雁来　五条');
INSERT INTO address VALUES  ('70826','北海道','札幌市　東区','東雁来　六条');
INSERT INTO address VALUES  ('70827','北海道','札幌市　東区','東雁来　七条');
INSERT INTO address VALUES  ('70828','北海道','札幌市　東区','東雁来　八条');
INSERT INTO address VALUES  ('70829','北海道','札幌市　東区','東雁来　九条');
INSERT INTO address VALUES  ('70030','北海道','札幌市　東区','東雁来　十条');
INSERT INTO address VALUES  ('70031','北海道','札幌市　東区','東雁来　十一条');
INSERT INTO address VALUES  ('70032','北海道','札幌市　東区','東雁来　十二条');
INSERT INTO address VALUES  ('70033','北海道','札幌市　東区','東雁来　十三条');
INSERT INTO address VALUES  ('70034','北海道','札幌市　東区','東雁来　十四条');
INSERT INTO address VALUES  ('70820','北海道','札幌市　東区','東雁来町');
INSERT INTO address VALUES  ('70801','北海道','札幌市　東区','東苗穂　一条');
INSERT INTO address VALUES  ('70802','北海道','札幌市　東区','東苗穂　二条');
INSERT INTO address VALUES  ('70803','北海道','札幌市　東区','東苗穂　三条');
INSERT INTO address VALUES  ('70804','北海道','札幌市　東区','東苗穂　四条');
INSERT INTO address VALUES  ('70805','北海道','札幌市　東区','東苗穂　五条');
INSERT INTO address VALUES  ('70806','北海道','札幌市　東区','東苗穂　六条');
INSERT INTO address VALUES  ('70807','北海道','札幌市　東区','東苗穂　七条');
INSERT INTO address VALUES  ('70808','北海道','札幌市　東区','東苗穂　八条');
INSERT INTO address VALUES  ('70809','北海道','札幌市　東区','東苗穂　九条');
INSERT INTO address VALUES  ('70810','北海道','札幌市　東区','東苗穂　十条');
INSERT INTO address VALUES  ('70811','北海道','札幌市　東区','東苗穂　十一条');
INSERT INTO address VALUES  ('70812','北海道','札幌市　東区','東苗穂　十二条');
INSERT INTO address VALUES  ('70813','北海道','札幌市　東区','東苗穂　十三条');
INSERT INTO address VALUES  ('70814','北海道','札幌市　東区','東苗穂　十四条');
INSERT INTO address VALUES  ('70815','北海道','札幌市　東区','東苗穂　十五条');
INSERT INTO address VALUES  ('70819','北海道','札幌市　東区','東苗穂町');
INSERT INTO address VALUES  ('70861','北海道','札幌市　東区','伏古　一条');
INSERT INTO address VALUES  ('70862','北海道','札幌市　東区','伏古　二条');
INSERT INTO address VALUES  ('70863','北海道','札幌市　東区','伏古　三条');
INSERT INTO address VALUES  ('70864','北海道','札幌市　東区','伏古　四条');
INSERT INTO address VALUES  ('70865','北海道','札幌市　東区','伏古　五条');
INSERT INTO address VALUES  ('70866','北海道','札幌市　東区','伏古　六条');
INSERT INTO address VALUES  ('70867','北海道','札幌市　東区','伏古　七条');
INSERT INTO address VALUES  ('70868','北海道','札幌市　東区','伏古　八条');
INSERT INTO address VALUES  ('70869','北海道','札幌市　東区','伏古　九条');
INSERT INTO address VALUES  ('70870','北海道','札幌市　東区','伏古　十条');
INSERT INTO address VALUES  ('70871','北海道','札幌市　東区','伏古　十一条');
INSERT INTO address VALUES  ('70872','北海道','札幌市　東区','伏古　十二条');
INSERT INTO address VALUES  ('70873','北海道','札幌市　東区','伏古　十三条');
INSERT INTO address VALUES  ('70874','北海道','札幌市　東区','伏古　十四条');
INSERT INTO address VALUES  ('650041','北海道','札幌市　東区','本町　一条');
INSERT INTO address VALUES  ('650042','北海道','札幌市　東区','本町　二条');
INSERT INTO address VALUES  ('70011','北海道','札幌市　東区','モエレ沼公園');
INSERT INTO address VALUES  ('30000','北海道','札幌市　白石区','以下に掲載がない場合');
INSERT INTO address VALUES  ('30851','北海道','札幌市　白石区','川北　一条');
INSERT INTO address VALUES  ('30852','北海道','札幌市　白石区','川北　二条');
INSERT INTO address VALUES  ('30853','北海道','札幌市　白石区','川北　三条');
INSERT INTO address VALUES  ('30854','北海道','札幌市　白石区','川北　四条');
INSERT INTO address VALUES  ('30855','北海道','札幌市　白石区','川北　五条');
INSERT INTO address VALUES  ('30869','北海道','札幌市　白石区','川下');
INSERT INTO address VALUES  ('30861','北海道','札幌市　白石区','川下　一条');
INSERT INTO address VALUES  ('30862','北海道','札幌市　白石区','川下　二条');
INSERT INTO address VALUES  ('30863','北海道','札幌市　白石区','川下　三条');
INSERT INTO address VALUES  ('30864','北海道','札幌市　白石区','川下　四条');
INSERT INTO address VALUES  ('30865','北海道','札幌市　白石区','川下　五条');
INSERT INTO address VALUES  ('30859','北海道','札幌市　白石区','川北');
INSERT INTO address VALUES  ('30801','北海道','札幌市　白石区','菊水　一条');
INSERT INTO address VALUES  ('30802','北海道','札幌市　白石区','菊水　二条');
INSERT INTO address VALUES  ('30803','北海道','札幌市　白石区','菊水　三条');
INSERT INTO address VALUES  ('30804','北海道','札幌市　白石区','菊水　四条');
INSERT INTO address VALUES  ('30805','北海道','札幌市　白石区','菊水　五条');
INSERT INTO address VALUES  ('30806','北海道','札幌市　白石区','菊水　六条');
INSERT INTO address VALUES  ('30807','北海道','札幌市　白石区','菊水　七条');
INSERT INTO address VALUES  ('30808','北海道','札幌市　白石区','菊水　八条');
INSERT INTO address VALUES  ('30809','北海道','札幌市　白石区','菊水　九条');
INSERT INTO address VALUES  ('30811','北海道','札幌市　白石区','菊水上町　一条');
INSERT INTO address VALUES  ('30812','北海道','札幌市　白石区','菊水上町　二条');
INSERT INTO address VALUES  ('30813','北海道','札幌市　白石区','菊水上町　三条');
INSERT INTO address VALUES  ('30814','北海道','札幌市　白石区','菊水上町　四条');
INSERT INTO address VALUES  ('30821','北海道','札幌市　白石区','菊水元町　一条');
INSERT INTO address VALUES  ('30822','北海道','札幌市　白石区','菊水元町　二条');
INSERT INTO address VALUES  ('30823','北海道','札幌市　白石区','菊水元町　三条');
INSERT INTO address VALUES  ('30824','北海道','札幌市　白石区','菊水元町　四条');
INSERT INTO address VALUES  ('30825','北海道','札幌市　白石区','菊水元町　五条');
INSERT INTO address VALUES  ('30826','北海道','札幌市　白石区','菊水元町　六条');
INSERT INTO address VALUES  ('30827','北海道','札幌市　白石区','菊水元町　七条');
INSERT INTO address VALUES  ('30828','北海道','札幌市　白石区','菊水元町　八条');
INSERT INTO address VALUES  ('30829','北海道','札幌市　白石区','菊水元町　九条');
INSERT INTO address VALUES  ('30830','北海道','札幌市　白石区','菊水元町　十条');
INSERT INTO address VALUES  ('30849','北海道','札幌市　白石区','北郷');
INSERT INTO address VALUES  ('30831','北海道','札幌市　白石区','北郷　一条');
INSERT INTO address VALUES  ('30832','北海道','札幌市　白石区','北郷　二条');
INSERT INTO address VALUES  ('30833','北海道','札幌市　白石区','北郷　三条');
INSERT INTO address VALUES  ('30834','北海道','札幌市　白石区','北郷　四条');
INSERT INTO address VALUES  ('30835','北海道','札幌市　白石区','北郷　五条');
INSERT INTO address VALUES  ('30836','北海道','札幌市　白石区','北郷　六条');
INSERT INTO address VALUES  ('30837','北海道','札幌市　白石区','北郷　七条');
INSERT INTO address VALUES  ('30838','北海道','札幌市　白石区','北郷　八条');
INSERT INTO address VALUES  ('30839','北海道','札幌市　白石区','北郷　九条');
INSERT INTO address VALUES  ('30840','北海道','札幌市　白石区','北郷　十条');
INSERT INTO address VALUES  ('30021','北海道','札幌市　白石区','栄通');
INSERT INTO address VALUES  ('30011','北海道','札幌市　白石区','中央　一条');
INSERT INTO address VALUES  ('30012','北海道','札幌市　白石区','中央　二条');
INSERT INTO address VALUES  ('30013','北海道','札幌市　白石区','中央　三条');
INSERT INTO address VALUES  ('30022','北海道','札幌市　白石区','南郷通（南）');
INSERT INTO address VALUES  ('30023','北海道','札幌市　白石区','南郷通（北）');
INSERT INTO address VALUES  ('30001','北海道','札幌市　白石区','東札幌　一条');
INSERT INTO address VALUES  ('30002','北海道','札幌市　白石区','東札幌　二条');
INSERT INTO address VALUES  ('30003','北海道','札幌市　白石区','東札幌　三条');
INSERT INTO address VALUES  ('30004','北海道','札幌市　白石区','東札幌　四条');
INSERT INTO address VALUES  ('30005','北海道','札幌市　白石区','東札幌　五条');
INSERT INTO address VALUES  ('30006','北海道','札幌市　白石区','東札幌　六条');
INSERT INTO address VALUES  ('30876','北海道','札幌市　白石区','東米里');
INSERT INTO address VALUES  ('30028','北海道','札幌市　白石区','平和通（南）');
INSERT INTO address VALUES  ('30029','北海道','札幌市　白石区','平和通（北）');
INSERT INTO address VALUES  ('30024','北海道','札幌市　白石区','本郷通（南）');
INSERT INTO address VALUES  ('30025','北海道','札幌市　白石区','本郷通（北）');
INSERT INTO address VALUES  ('30026','北海道','札幌市　白石区','本通（南）');
INSERT INTO address VALUES  ('30027','北海道','札幌市　白石区','本通（北）');
INSERT INTO address VALUES  ('30871','北海道','札幌市　白石区','米里　一条');
INSERT INTO address VALUES  ('30872','北海道','札幌市　白石区','米里　二条');
INSERT INTO address VALUES  ('30873','北海道','札幌市　白石区','米里　三条');
INSERT INTO address VALUES  ('30874','北海道','札幌市　白石区','米里　四条');
INSERT INTO address VALUES  ('30875','北海道','札幌市　白石区','米里　五条');
INSERT INTO address VALUES  ('30030','北海道','札幌市　白石区','流通センター');
INSERT INTO address VALUES  ('620000','北海道','札幌市　豊平区','以下に掲載がない場合');
INSERT INTO address VALUES  ('620911','北海道','札幌市　豊平区','旭町');
INSERT INTO address VALUES  ('620912','北海道','札幌市　豊平区','水車町');
INSERT INTO address VALUES  ('620020','北海道','札幌市　豊平区','月寒　中央通');
INSERT INTO address VALUES  ('620021','北海道','札幌市　豊平区','月寒　西一条');
INSERT INTO address VALUES  ('620022','北海道','札幌市　豊平区','月寒　西二条');
INSERT INTO address VALUES  ('620023','北海道','札幌市　豊平区','月寒　西三条');
INSERT INTO address VALUES  ('620024','北海道','札幌市　豊平区','月寒　西四条');
INSERT INTO address VALUES  ('620025','北海道','札幌市　豊平区','月寒　西五条');
INSERT INTO address VALUES  ('620051','北海道','札幌市　豊平区','月寒　東一条');
INSERT INTO address VALUES  ('620052','北海道','札幌市　豊平区','月寒　東二条');
INSERT INTO address VALUES  ('620053','北海道','札幌市　豊平区','月寒　東三条');
INSERT INTO address VALUES  ('620054','北海道','札幌市　豊平区','月寒　東四条');
INSERT INTO address VALUES  ('620055','北海道','札幌市　豊平区','月寒　東五条');
INSERT INTO address VALUES  ('620901','北海道','札幌市　豊平区','豊平　一条');
INSERT INTO address VALUES  ('620902','北海道','札幌市　豊平区','豊平　二条');
INSERT INTO address VALUES  ('620903','北海道','札幌市　豊平区','豊平　三条');
INSERT INTO address VALUES  ('620904','北海道','札幌市　豊平区','豊平　四条');
INSERT INTO address VALUES  ('620905','北海道','札幌市　豊平区','豊平　五条');
INSERT INTO address VALUES  ('620906','北海道','札幌市　豊平区','豊平　六条');
INSERT INTO address VALUES  ('620907','北海道','札幌市　豊平区','豊平　七条');
INSERT INTO address VALUES  ('620908','北海道','札幌市　豊平区','豊平　八条');
INSERT INTO address VALUES  ('620909','北海道','札幌市　豊平区','豊平　九条');
INSERT INTO address VALUES  ('620921','北海道','札幌市　豊平区','中の島　一条');
INSERT INTO address VALUES  ('620922','北海道','札幌市　豊平区','中の島　二条');
INSERT INTO address VALUES  ('620039','北海道','札幌市　豊平区','西岡');
INSERT INTO address VALUES  ('620031','北海道','札幌市　豊平区','西岡　一条');
INSERT INTO address VALUES  ('620032','北海道','札幌市　豊平区','西岡　二条');
INSERT INTO address VALUES  ('620033','北海道','札幌市　豊平区','西岡　三条');
INSERT INTO address VALUES  ('620034','北海道','札幌市　豊平区','西岡　四条');
INSERT INTO address VALUES  ('620035','北海道','札幌市　豊平区','西岡　五条');
INSERT INTO address VALUES  ('620045','北海道','札幌市　豊平区','羊ケ丘');
INSERT INTO address VALUES  ('620931','北海道','札幌市　豊平区','平岸　一条');
INSERT INTO address VALUES  ('620932','北海道','札幌市　豊平区','平岸　二条');
INSERT INTO address VALUES  ('620933','北海道','札幌市　豊平区','平岸　三条');
INSERT INTO address VALUES  ('620934','北海道','札幌市　豊平区','平岸　四条');
INSERT INTO address VALUES  ('620935','北海道','札幌市　豊平区','平岸　五条');
INSERT INTO address VALUES  ('620936','北海道','札幌市　豊平区','平岸　六条');
INSERT INTO address VALUES  ('620937','北海道','札幌市　豊平区','平岸　七条');
INSERT INTO address VALUES  ('620938','北海道','札幌市　豊平区','平岸　八条');
INSERT INTO address VALUES  ('620041','北海道','札幌市　豊平区','福住　一条');
INSERT INTO address VALUES  ('620042','北海道','札幌市　豊平区','福住　二条');
INSERT INTO address VALUES  ('620043','北海道','札幌市　豊平区','福住　三条');
INSERT INTO address VALUES  ('620001','北海道','札幌市　豊平区','美園　一条');
INSERT INTO address VALUES  ('620002','北海道','札幌市　豊平区','美園　二条');
INSERT INTO address VALUES  ('620003','北海道','札幌市　豊平区','美園　三条');
INSERT INTO address VALUES  ('620004','北海道','札幌市　豊平区','美園　四条');
INSERT INTO address VALUES  ('620005','北海道','札幌市　豊平区','美園　五条');
INSERT INTO address VALUES  ('620006','北海道','札幌市　豊平区','美園　六条');
INSERT INTO address VALUES  ('620007','北海道','札幌市　豊平区','美園　七条');
INSERT INTO address VALUES  ('620008','北海道','札幌市　豊平区','美園　八条');
INSERT INTO address VALUES  ('620009','北海道','札幌市　豊平区','美園　九条');
INSERT INTO address VALUES  ('620010','北海道','札幌市　豊平区','美園　十条');
INSERT INTO address VALUES  ('620011','北海道','札幌市　豊平区','美園　十一条');
INSERT INTO address VALUES  ('620012','北海道','札幌市　豊平区','美園　十二条');
INSERT INTO address VALUES  ('50000','北海道','札幌市　南区','以下に掲載がない場合');
INSERT INTO address VALUES  ('50849','北海道','札幌市　南区','石山');
INSERT INTO address VALUES  ('50850','北海道','札幌市　南区','石山　東');
INSERT INTO address VALUES  ('50841','北海道','札幌市　南区','石山　一条');
INSERT INTO address VALUES  ('50842','北海道','札幌市　南区','石山　二条');
INSERT INTO address VALUES  ('50843','北海道','札幌市　南区','石山　三条');
INSERT INTO address VALUES  ('50844','北海道','札幌市　南区','石山　四条');
INSERT INTO address VALUES  ('50801','北海道','札幌市　南区','川沿　一条');
INSERT INTO address VALUES  ('50802','北海道','札幌市　南区','川沿　二条');
INSERT INTO address VALUES  ('50803','北海道','札幌市　南区','川沿　三条');
INSERT INTO address VALUES  ('50804','北海道','札幌市　南区','川沿　四条');
INSERT INTO address VALUES  ('50805','北海道','札幌市　南区','川沿　五条');
INSERT INTO address VALUES  ('50806','北海道','札幌市　南区','川沿　六条');
INSERT INTO address VALUES  ('50807','北海道','札幌市　南区','川沿　七条');
INSERT INTO address VALUES  ('50808','北海道','札幌市　南区','川沿　八条');
INSERT INTO address VALUES  ('50809','北海道','札幌市　南区','川沿　九条');
INSERT INTO address VALUES  ('50810','北海道','札幌市　南区','川沿　十条');
INSERT INTO address VALUES  ('50811','北海道','札幌市　南区','川沿　十一条');
INSERT INTO address VALUES  ('50812','北海道','札幌市　南区','川沿　十二条');
INSERT INTO address VALUES  ('50813','北海道','札幌市　南区','川沿　十三条');
INSERT INTO address VALUES  ('50814','北海道','札幌市　南区','川沿　十四条');
INSERT INTO address VALUES  ('50815','北海道','札幌市　南区','川沿　十五条');
INSERT INTO address VALUES  ('50816','北海道','札幌市　南区','川沿　十六条');
INSERT INTO address VALUES  ('50817','北海道','札幌市　南区','川沿　十七条');
INSERT INTO address VALUES  ('50818','北海道','札幌市　南区','川沿　十八条');
INSERT INTO address VALUES  ('50832','北海道','札幌市　南区','北ノ沢');
INSERT INTO address VALUES  ('50864','北海道','札幌市　南区','芸術の森');
INSERT INTO address VALUES  ('612274','北海道','札幌市　南区','小金湯');
INSERT INTO address VALUES  ('612301','北海道','札幌市　南区','定山渓');
INSERT INTO address VALUES  ('612302','北海道','札幌市　南区','定山渓温泉東');
INSERT INTO address VALUES  ('612303','北海道','札幌市　南区','定山渓温泉西');
INSERT INTO address VALUES  ('612276','北海道','札幌市　南区','白川');
INSERT INTO address VALUES  ('50007','北海道','札幌市　南区','澄川');
INSERT INTO address VALUES  ('50001','北海道','札幌市　南区','澄川　一条');
INSERT INTO address VALUES  ('50002','北海道','札幌市　南区','澄川　二条');
INSERT INTO address VALUES  ('50003','北海道','札幌市　南区','澄川　三条');
INSERT INTO address VALUES  ('50004','北海道','札幌市　南区','澄川　四条');
INSERT INTO address VALUES  ('50005','北海道','札幌市　南区','澄川　五条');
INSERT INTO address VALUES  ('50006','北海道','札幌市　南区','澄川　六条');
INSERT INTO address VALUES  ('50862','北海道','札幌市　南区','滝野');
INSERT INTO address VALUES  ('50830','北海道','札幌市　南区','砥石山');
INSERT INTO address VALUES  ('50865','北海道','札幌市　南区','常盤（１～１３１番地）');
INSERT INTO address VALUES  ('50863','北海道','札幌市　南区','常盤（その他）');
INSERT INTO address VALUES  ('50851','北海道','札幌市　南区','常盤一条');
INSERT INTO address VALUES  ('50852','北海道','札幌市　南区','常盤二条');
INSERT INTO address VALUES  ('50853','北海道','札幌市　南区','常盤三条');
INSERT INTO address VALUES  ('50854','北海道','札幌市　南区','常盤四条');
INSERT INTO address VALUES  ('50855','北海道','札幌市　南区','常盤五条');
INSERT INTO address VALUES  ('50856','北海道','札幌市　南区','常盤六条');
INSERT INTO address VALUES  ('612275','北海道','札幌市　南区','砥山');
INSERT INTO address VALUES  ('612273','北海道','札幌市　南区','豊滝');
INSERT INTO address VALUES  ('50831','北海道','札幌市　南区','中ノ沢');
INSERT INTO address VALUES  ('50840','北海道','札幌市　南区','藤野（４００、４００－２番地）');
INSERT INTO address VALUES  ('612271','北海道','札幌市　南区','藤野（その他）');
INSERT INTO address VALUES  ('612281','北海道','札幌市　南区','藤野　一条');
INSERT INTO address VALUES  ('612282','北海道','札幌市　南区','藤野　二条');
INSERT INTO address VALUES  ('612283','北海道','札幌市　南区','藤野　三条');
INSERT INTO address VALUES  ('612284','北海道','札幌市　南区','藤野　四条');
INSERT INTO address VALUES  ('612285','北海道','札幌市　南区','藤野　五条');
INSERT INTO address VALUES  ('612286','北海道','札幌市　南区','藤野　六条');
INSERT INTO address VALUES  ('50008','北海道','札幌市　南区','真駒内（１７番地）');
INSERT INTO address VALUES  ('50861','北海道','札幌市　南区','真駒内（その他）');
INSERT INTO address VALUES  ('50018','北海道','札幌市　南区','真駒内曙町');
INSERT INTO address VALUES  ('50015','北海道','札幌市　南区','真駒内泉町');
INSERT INTO address VALUES  ('50022','北海道','札幌市　南区','真駒内柏丘');
INSERT INTO address VALUES  ('50012','北海道','札幌市　南区','真駒内上町');
INSERT INTO address VALUES  ('50014','北海道','札幌市　南区','真駒内幸町');
INSERT INTO address VALUES  ('50011','北海道','札幌市　南区','真駒内東町');
INSERT INTO address VALUES  ('50021','北海道','札幌市　南区','真駒内本町');
INSERT INTO address VALUES  ('50013','北海道','札幌市　南区','真駒内緑町');
INSERT INTO address VALUES  ('50016','北海道','札幌市　南区','真駒内南町');
INSERT INTO address VALUES  ('50017','北海道','札幌市　南区','真駒内公園');
INSERT INTO address VALUES  ('612261','北海道','札幌市　南区','簾舞　一条');
INSERT INTO address VALUES  ('612262','北海道','札幌市　南区','簾舞　二条');
INSERT INTO address VALUES  ('612263','北海道','札幌市　南区','簾舞　三条');
INSERT INTO address VALUES  ('612264','北海道','札幌市　南区','簾舞　四条');
INSERT INTO address VALUES  ('612265','北海道','札幌市　南区','簾舞　五条');
INSERT INTO address VALUES  ('612266','北海道','札幌市　南区','簾舞　六条');
INSERT INTO address VALUES  ('612272','北海道','札幌市　南区','簾舞（その他）');
INSERT INTO address VALUES  ('50827','北海道','札幌市　南区','南沢');
INSERT INTO address VALUES  ('50821','北海道','札幌市　南区','南沢一条');
INSERT INTO address VALUES  ('50822','北海道','札幌市　南区','南沢二条');
INSERT INTO address VALUES  ('50823','北海道','札幌市　南区','南沢三条');
INSERT INTO address VALUES  ('50824','北海道','札幌市　南区','南沢四条');
INSERT INTO address VALUES  ('50825','北海道','札幌市　南区','南沢五条');
INSERT INTO address VALUES  ('50826','北海道','札幌市　南区','南沢六条');
INSERT INTO address VALUES  ('50030','北海道','札幌市　南区','南三十条西（８丁目）');
INSERT INTO address VALUES  ('50031','北海道','札幌市　南区','南三十一条西');
INSERT INTO address VALUES  ('50032','北海道','札幌市　南区','南三十二条西');
INSERT INTO address VALUES  ('50033','北海道','札幌市　南区','南三十三条西');
INSERT INTO address VALUES  ('50034','北海道','札幌市　南区','南三十四条西');
INSERT INTO address VALUES  ('50035','北海道','札幌市　南区','南三十五条西');
INSERT INTO address VALUES  ('50036','北海道','札幌市　南区','南三十六条西');
INSERT INTO address VALUES  ('50037','北海道','札幌市　南区','南三十七条西');
INSERT INTO address VALUES  ('50038','北海道','札幌市　南区','南三十八条西');
INSERT INTO address VALUES  ('50039','北海道','札幌市　南区','南三十九条西');
INSERT INTO address VALUES  ('50040','北海道','札幌市　南区','藻岩下');
INSERT INTO address VALUES  ('50041','北海道','札幌市　南区','藻岩山');
INSERT INTO address VALUES  ('630000','北海道','札幌市　西区','以下に掲載がない場合');
INSERT INTO address VALUES  ('630811','北海道','札幌市　西区','琴似　一条');
INSERT INTO address VALUES  ('630812','北海道','札幌市　西区','琴似　二条');
INSERT INTO address VALUES  ('630813','北海道','札幌市　西区','琴似　三条');
INSERT INTO address VALUES  ('630814','北海道','札幌市　西区','琴似　四条');
INSERT INTO address VALUES  ('630011','北海道','札幌市　西区','小別沢');
INSERT INTO address VALUES  ('630049','北海道','札幌市　西区','西野');
INSERT INTO address VALUES  ('630031','北海道','札幌市　西区','西野　一条');
INSERT INTO address VALUES  ('630032','北海道','札幌市　西区','西野　二条');
INSERT INTO address VALUES  ('630033','北海道','札幌市　西区','西野　三条');
INSERT INTO address VALUES  ('630034','北海道','札幌市　西区','西野　四条');
INSERT INTO address VALUES  ('630035','北海道','札幌市　西区','西野　五条');
INSERT INTO address VALUES  ('630036','北海道','札幌市　西区','西野　六条');
INSERT INTO address VALUES  ('630037','北海道','札幌市　西区','西野　七条');
INSERT INTO address VALUES  ('630038','北海道','札幌市　西区','西野　八条');
INSERT INTO address VALUES  ('630039','北海道','札幌市　西区','西野　九条');
INSERT INTO address VALUES  ('630040','北海道','札幌市　西区','西野　十条');
INSERT INTO address VALUES  ('630041','北海道','札幌市　西区','西野　十一条');
INSERT INTO address VALUES  ('630042','北海道','札幌市　西区','西野　十二条');
INSERT INTO address VALUES  ('630043','北海道','札幌市　西区','西野　十三条');
INSERT INTO address VALUES  ('630044','北海道','札幌市　西区','西野　十四条');
INSERT INTO address VALUES  ('630062','北海道','札幌市　西区','西町南');
INSERT INTO address VALUES  ('630061','北海道','札幌市　西区','西町北');
INSERT INTO address VALUES  ('630801','北海道','札幌市　西区','二十四軒　一条');
INSERT INTO address VALUES  ('630802','北海道','札幌市　西区','二十四軒　二条');
INSERT INTO address VALUES  ('630803','北海道','札幌市　西区','二十四軒　三条');
INSERT INTO address VALUES  ('630804','北海道','札幌市　西区','二十四軒　四条');
INSERT INTO address VALUES  ('630861','北海道','札幌市　西区','八軒　一条東');
INSERT INTO address VALUES  ('630841','北海道','札幌市　西区','八軒　一条西');
INSERT INTO address VALUES  ('630862','北海道','札幌市　西区','八軒　二条東');
INSERT INTO address VALUES  ('630842','北海道','札幌市　西区','八軒　二条西');
INSERT INTO address VALUES  ('630863','北海道','札幌市　西区','八軒　三条東');
INSERT INTO address VALUES  ('630843','北海道','札幌市　西区','八軒　三条西');
INSERT INTO address VALUES  ('630864','北海道','札幌市　西区','八軒　四条東');
INSERT INTO address VALUES  ('630844','北海道','札幌市　西区','八軒　四条西');
INSERT INTO address VALUES  ('630865','北海道','札幌市　西区','八軒　五条東');
INSERT INTO address VALUES  ('630845','北海道','札幌市　西区','八軒　五条西');
INSERT INTO address VALUES  ('630866','北海道','札幌市　西区','八軒　六条東');
INSERT INTO address VALUES  ('630846','北海道','札幌市　西区','八軒　六条西');
INSERT INTO address VALUES  ('630867','北海道','札幌市　西区','八軒　七条東');
INSERT INTO address VALUES  ('630847','北海道','札幌市　西区','八軒　七条西');
INSERT INTO address VALUES  ('630868','北海道','札幌市　西区','八軒　八条東');
